//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingsman.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSizes
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> StandartedSize { get; set; }
        public Nullable<decimal> HeadDiameter { get; set; }
        public Nullable<decimal> ShoulderDistance { get; set; }
        public Nullable<decimal> ChestSize { get; set; }
        public Nullable<decimal> HandLenght { get; set; }
        public Nullable<decimal> WaistDiameter { get; set; }
        public Nullable<decimal> HipsDiameter { get; set; }
        public Nullable<decimal> LegLenght { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
