//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingsman.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePhoto
    {
        public int Id { get; set; }
        public string PhotoLink { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Description { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
