//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingsman.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierDelivery
    {
        public int Id { get; set; }
        public Nullable<int> SupllierId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
